name: Optimize resource pack
on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          allow_optifine_mod: true
          zip_spec_conformance_level: balanced
          never_store_squash_times: true
          transcode_ogg: false
          always_allow_json_comments: false
          maximum_image_width_and_height: 12288
