name: Optimize resource pack
on: [push]
jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          allow_optifine_mod: true
          zip_spec_conformance_level: disregard
          transcode_ogg: false
