name: Optimize resource pack
on: workflow_dispatch
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          allow_optifine_mod: true
          zip_spec_conformance_level: disregard
          never_store_squash_times: true
          transcode_ogg: false
          always_allow_json_comments: false
          maximum_width_and_height: 65536